global:
  scrape_interval: 5s

  external_labels:
    monitor: 'open5gs-monitor'

scrape_configs:
  - job_name: 'amf'
    static_configs:
      - targets: ['amf:9091']
  - job_name: 'smf'
    static_configs:
      - targets: ['smf:9091']
  - job_name: 'pcf'
    static_configs:
      - targets: ['pcf:9091']
  - job_name: 'upf'
    static_configs:
      - targets: ['upf:9091']
  - job_name: 'mme'
    static_configs:
      - targets: ['mme:9091']
