amf:
  addr: amf                                                                              # The address or hostname of the AMF.
  bind_addr: $GNB_IP                                                                       # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: zmq                                                                          # The RF driver name.
  # device_args: tx_port=tcp://$GNB_IP:2000,rx_port=tcp://$UE_IP:2001,base_srate=23.04e6  # Optionally pass arguments to the selected RF driver.
  # device_args: tx_port=tcp://$GNB_IP:2000,rx_port=tcp://172.30.0.201:2100,base_srate=23.04e6  # Optionally pass arguments to the selected RF driver.
  device_args: tx_port=tcp://$GNB_IP:2000,rx_port=tcp://$ZMQ_RX_IP:2000,base_srate=23.04e6
  srate: 23.04                                                                                # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 75                                                                                 # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 75                                                                                 # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 368500                                                                            # ARFCN of the downlink carrier (center frequency).
  band: 3                                                                                     # The NR band.
  channel_bandwidth_MHz: 20                                                                   # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                                                                              # Subcarrier spacing in kHz used for data.
  plmn: "$MCC$MNC"                                                                                # PLMN broadcasted by the gNB.
  tac: 1                                                                                      # Tracking area code (needs to match the core configuration).
  pci: 1                                                                                      # Physical cell ID.
  pdcch:
    dedicated:
      ss2_type: common                                                                        # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false                                                           # Set correct DCI format (fallback)
    common:
      ss0_index: 0
      coreset0_index: 13
  prach:
    prach_config_index: 1
    total_nof_ra_preambles: 63

log:
  filename: /mnt/srsran/gnb.log                                                               # Path of the log file.
  all_level: warning                                                                          # Logging level applied to all layers.

pcap:
  mac_enable: false                                                                           # Set to true to enable MAC-layer PCAPs.
  mac_filename: /mnt/srsran/gnb_mac.pcap                                                      # Path where the MAC PCAP is stored.
  ngap_enable: false                                                                          # Set to true to enable NGAP PCAPs.
  ngap_filename: /mnt/srsran/gnb_ngap.pcap                                                    # Path where the NGAP PCAP is stored.
  f1ap_enable: false                                                                          # Set to true to enable F1AP PCAPs.
  f1ap_filename: /mnt/srsran/gnb_f1ap.pcap                                                    # Path where the F1AP PCAP is stored.
  e1ap_enable: false                                                                          # Set to true to enable E1AP PCAPs.
  e1ap_filename: /mnt/srsran/gnb_e1ap.pcap                                                    # Path where the E1AP PCAP is stored.
  e2ap_enable: false                                                                          # Set to true to enable E2AP PCAPs.
  e2ap_filename: /mnt/srsran/gnb_e2ap.pcap                                                    # Path where the E2AP PCAP is stored.
  gtpu_enable: false                                                                          # Set to true to enable GTP-U PCAPs.
  gtpu_filename: /mnt/srsran/gnb_gtpu.pcap                                                    # Path where the GTP-U PCAP is stored.

e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  addr: ric                   # RIC IP address
  bind_addr: $GNB_IP
  port: 36421                       # RIC port

metrics:
  rlc_json_enable: 1                # Enable RLC metrics reporting
  rlc_report_period: 1000           # Set reporting period to 1s
