logger:
    file: 
        path: /open5gs/install/var/log/open5gs/ausf.log

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: $MAX_NUM_UE

ausf:
    sbi:
      server:
        - address: ausf
          port: 80
      client:
        nrf:
          - uri: http://nrf:80
        scp:
          - uri: http://scp:80
