logger:
    file: 
        path: /open5gs/install/var/log/open5gs/smf.log

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: $MAX_NUM_UE
  parameter:
      no_ipv4v6_local_addr_in_packet_filter: true

smf:
    freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf
    sbi:
      server:
        - address: smf
          port: 80
      client:
        nrf:
          - uri: http://nrf:80
        scp:
          - uri: http://scp:80
    gtpc:
      server:
        - address: smf
    gtpu:
      server:
        - address: smf
    pfcp:
      server:
        - address: smf
      client:
        upf:
          - address: upf
    session:
      - subnet: $UE_IPV4_INTERNET_RANGE
        gateway: $UE_IPV4_INTERNET_GATEWAY
        dnn: internet
        dev: ogstun
      - subnet: 2001:230:cafe::/48
        gateway: 2001:230:cafe::1
        dnn: internet
        dev: ogstun
      - subnet: $UE_IPV4_IMS_RANGE
        gateway: $UE_IPV4_IMS_GATEWAY
        dnn: ims
        dev: ogstun2
      - subnet: 2001:230:babe::/48
        gateway: 2001:230:cafe::1
        dnn: ims
        dev: ogstun2
    dns:
      - $SMF_DNS1
      - $SMF_DNS2
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    p-cscf:
      - 127.0.0.1
    mtu: 1450
    metrics:
      server:
        - address: smf
          port: 9091
