logger:
    file: 
        path: /open5gs/install/var/log/open5gs/nssf.log

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: $MAX_NUM_UE

nssf:
    sbi:
      server:
        - address: nssf
          port: 80
      client:
        nrf:
          - uri: http://nrf:80
        scp:
          - uri: http://scp:80
        nsi:
          - uri: http://nrf:80
            s_nssai:
              sst: 1

