logger:
    file: 
        path: /open5gs/install/var/log/open5gs/upf.log

global:
  max:
    ue: $MAX_NUM_UE

upf:
    pfcp:
      server:
        - address: upf
      client:
        smf:
          - address: smf
    gtpu:
      server:
        - address: upf
          advertise: upf
    session:
      - subnet: $UE_IPV4_INTERNET_RANGE
        gateway: $UE_IPV4_INTERNET_GATEWAY
        dnn: internet
        dev: ogstun
      - subnet: 2001:230:cafe::/48
        gateway: 2001:230:cafe::1
        dnn: internet
        dev: ogstun
      - subnet: $UE_IPV4_IMS_RANGE
        gateway: $UE_IPV4_IMS_GATEWAY
        dnn: ims
        dev: ogstun2
      - subnet: 2001:230:babe::/48
        gateway: 2001:230:cafe::1
        dnn: ims
        dev: ogstun2
    metrics:
      server:
        - address: upf
          port: 9091
